### PR TITLE
Moving base Confetti Framework components

### PR DESCRIPTION
**Pull request by octoper**
This PR removes the following import in favor of `github.com/confetti-framework/framework`

 - `github.com/confetti-framework/contract`
 - `github.com/confetti-framework/foundation`
 - `github.com/confetti-framework/support`
 - `github.com/confetti-framework/validation`

### CODE REVIEW

**Review by reindert-vetter — APPROVED** [review]
Approval, but maybe we should move github.com/confetti-framework/framework/contract/inter to github.com/confetti-framework/framework/inter (see other issue)

**Comment by octoper** [comment]
Okay I will try move it later today!

**Comment by octoper** [comment]
Just moved `github.com/confetti-framework/framework/contract/inter` to `github.com/confetti-framework/framework/inter`

**Comment by reindert-vetter** [comment]
Very nice! Is there anything else that needs to be done? In that case, I'll test it today.

I will also refactor https://github.com/confetti-framework/commands to the framework repo. That's a stripped-down version of the confetti framework.

**Comment by octoper** [comment]
Νο everything is fine from my side.
The only thing remains is to create a readme and a contribution guide.

**Comment by reindert-vetter** [comment]
It all works fine. I've also updated repo commands.

Baker just doesn't work 😢 : 

```
➜  confetti git:(framework) ✗ go run . baker
Baker  :help for help
 > app.Log().Info("test")
/Users/reindertvetter/go/pkg/mod/github.com/mattn/go-colorable@v0.1.7/colorable_others.go:10:2: missing go.sum entry for module providing package github.com/mattn/go-isatty (imported by github.com/mattn/go-colorable); to add:
	go get github.com/mattn/go-colorable@v0.1.7
```

I don't see how quickly I can solve the problem. Do you have an idea?

I've been busy updating repo baker with the upstream today. After resolving conflicts, tests fail in that repo, so I need to troubleshoot those further (see https://github.com/confetti-framework/baker/pull/3)

**Comment by reindert-vetter** [comment]
I think it works now. It must have been my environment. I'll merge it and make a release for it.

**Comment by reindert-vetter** [comment]
https://github.com/confetti-framework/confetti/releases/tag/v0.29.0 🥳 

Thanks for all your work!

**Pull request merged**
